import Head from 'next/head'
import Image from 'next/image'

import Card from '../components/card'

import Image2k from '../assets/image-2k.png'
import Image4k from '../assets/image-4k.png'
import Image720p from '../assets/image-720p.png'
import Image1080p from '../assets/image-1080p.png'

import styles from '../styles/Home.module.css'

const Home = () => {
    return (
        <div className={styles.container}>
            <Head>
                <title>Next Image Blur</title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <link rel='icon' href='/favicon.ico' />
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>
                    <a href='https://nextjs.org'>Next.js</a> Image Blur
                </h1>

                <div className={styles.content}>
                    <Card headline='720p Image Resolution' image={Image720p} />
                </div>
            </main>

            <footer className={styles.footer}>
                <a
                    href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
                    target='_blank'
                    rel='noopener noreferrer'
                >
                    Powered by{' '}
                    <span className={styles.logo}>
                        <Image
                            src='/vercel.svg'
                            alt='Vercel Logo'
                            width={72}
                            height={16}
                        />
                    </span>
                </a>
            </footer>
        </div>
    )
}

export default Home
